### ISSUE TITLE
Gazebo cheat mode

### ISSUE THREAD

**Issue by KahnShi** [tongtybj/aerial_robot#36]
@tongtybj 
1. Adjust torque_force rate 
2.  Increase joint velocity
3. Add yaw velocity control in /uav/uav topic (currently missing)

**Comment by KahnShi** [comment]
@tongtybj 
Trying to use velocity control for joints but failed.
I did in following way
`rostopic pub /hydrus3/joints_ctrl sensor_msgs/JointState "header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
name: ['']`
`position: [0]`
`velocity: [0, 0, -0.1]`
`effort: [0]" 
`
and simulation gave me such error:
![screenshot from 2017-05-18 19-19-33](https://cloud.githubusercontent.com/assets/6027941/26198053/8652414e-3bff-11e7-90c3-331c1dad1a48.png)

**Comment by tongtybj** [comment]
1. I did not implement the joint velocity control mode, only position control mode
2. The error means the number of ``` position[] ``` in  ``` sensor_msgs/JointState``` is not equal with the joint number(e.g. 3 for hydrus3). Since you only set the ```velocity[]``` with correct elements, but no elements in ```position[]```

**Comment by tongtybj** [comment]
@KahnShi 
I think we should create another issue to discuss the joint velocity control mode
