### ISSUE TITLE
[rosserial] bad fixed size of ros msg

### ISSUE THREAD

**Issue by chibi314** [tongtybj/aerial_robot#45]
Please fix this:
https://github.com/tongtybj/aerial_robot/blob/devel/hydrus/hydrus_transform_control/src/transform_control.cpp#L828-L837

Check:
http://answers.ros.org/question/10988/use-multiarray-in-rosserial/

**Comment by tongtybj** [comment]
The additional elements for the array type is "xxxx_length", which has 4 bytes.
Please refer [``` aerial_robot_msgs::FourAxisGain ```](https://github.com/tongtybj/rosserial/blob/master/rosserial_stm/test/ros_lib/aerial_robot_msgs/FourAxisGain.h)

**Comment by tongtybj** [comment]
Solved by #52
