### ISSUE TITLE
Gazebo

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/aerial_robot#6]
@KahnShi @chibi314 

The basic knowledge for gazebo ros interface:

1. [ros_control in gazebo](http://gazebosim.org/tutorials?tut=ros_control&cat=connect_ros)
Basic tutorial and introduction for  gazebo control.

2. [gazebo_ros_control_plugin](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_ros_control/src/gazebo_ros_control_plugin.cpp)
The hardware interface in wide sense. Parsing transmission elements, create instance about the "hw interface sim" and "controller_manager_". Execute "readSim", "writeSim" and "controller_manager_->update".

3. [default_robot_hw_sim](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_ros_control/src/default_robot_hw_sim.cpp)
The hardware interface in narrow sense. Create the instance for specific hardware interface (i.e joint, motor twist in UAV). Define the func of "ReadSim" and "WriteSim".

4. [hector_quadcopter](https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor)
The code for rigid UAV in gazebo. The core code should be [here](https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/blob/indigo-devel/hector_quadrotor_controller_gazebo/src/quadrotor_hardware_gazebo.cpp)

- Transmission:
Connecting specific hardware_interface(joint, motor twist in UAV) and actuator_interface, check the [example](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_ros_control/src/default_robot_hw_sim.cpp#L105-L116)

- The connection between controller and HW.
controlller is called from controlller_spawner, while the HW is called from gazebo_ros_control_plugin. The connection between controller and HW is based on pointer(?). Please check the hector code.
Also check [this code](https://github.com/ros-controls/ros_control/blob/kinetic-devel/controller_manager/scripts/spawner)

**Comment by chibi314** [comment]
[これ](https://github.com/tongtybj/aerial_robot/blob/devel/aerial_robot_model/robots/hydrus3.urdf.xacro)のrobot nameがhydra3になってます．

**Comment by tongtybj** [comment]
@chibi314 
#17 で直しました。
</robotNamespace>は基本rosnodeのprefix的なことをしてて、あまり影響はないようです。

**Comment by tongtybj** [comment]
@chibi314 @KahnShi 
I finish the most of the simulation work to check the flight control and basic navigation in the gazebo for aerial robot. Please check #23.

However, I only complete the platform for hydrus3 which is the old type of 2D transformable aerial robot. I will implement for latest  hydrusx series in a week.

I will teach you how to use after the travis confirm the compile.

**Comment by tongtybj** [comment]
the basic command in gazebo:
```
$ roslaunch hydrus_transform_control hydrus3_bringup.launch real_machine:=false simulation:=true headless:=false control_mode:=0
$ rosrun aerial_robot_base keyboard_command.py 
```
In the terminal of ``` keyboard_command.py ```, please enter ```r ``` to arm the motor and then enter ``` t``` to takeoff, ``` l``` to land.
``` control_mode  = 0 ``` means the position control.
